version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - '80:80'
        volumes:
            - ./webapp:/code
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - web

    web:
        build:
            context: ./webapp
            dockerfile: Dockerfile
        command: uvicorn webapp.asgi:application --host 0.0.0.0 -port 8000
        volumes:
            - ./webapp:/code
        expose:
            - '8000'
