version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - '80:80'
        volumes:
            - ./webapp:/code
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - web
        networks:
            - net

    web:
        build:
            context: ./webapp
            dockerfile: Dockerfile
        command: gunicorn webapp.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - ./webapp:/code
        expose:
            - '8000'
        networks:
            - net
networks:
    net:
        driver: bridge
